# example 1: on push to master
name: Bump version
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-22.04
    outputs:
      version: ${{ steps.autotag.outputs.new_tag }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: "0"

      - name: Bump version and push tag
        id: autotag
        uses: anothrNick/github-tag-action@1.58.0 # Don't use @master unless you're happy to test the latest version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BRANCH: main

  test:
    name: test
    needs: ["build"]
    runs-on: ubuntu-latest
    steps:
      - name: Log outputs from previous action
        run: |
          echo ${{needs.build.outputs.version}}
