# example 1: on push to master
name: Bump version
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: "0"

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.55.0 # Don't use @master unless you're happy to test the latest version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true

  test:
    name: test
    needs: ["build"]
    runs-on: ubuntu-latest
    steps:
      - name: Log outputs from previous action
        run: |
          echo ${{needs.build.outputs.new_tag}}  >> $GITHUB_OUTPUT
          echo ${{needs.build.outputs.tag}}  >> $GITHUB_OUTPUT
          echo "${{needs.build.outputs.part}}"  >> $GITHUB_OUTPUT
          echo "${{needs.build.outputs.status}}"  >> $GITHUB_OUTPUT
          echo "${{needs.build.outputs}}"  >> $GITHUB_OUTPUT
