name: Check Version Bump

on: [push, pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Get main version
        id: tm
        run: |
          ls
          echo "MAINV=$(jq -r '.version' version.json)" >> $GITHUB_OUTPUT

      - name: Checkout PR
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Get PR version
        id: tpr
        run: |
          ls
          echo "PRV=$(jq -r '.version' version.json)" >> $GITHUB_OUTPUT

      - name: Compare versions
        run: |
          if [ ${{steps.tm.outputs.MAINV}} != ${{steps.tpr.outputs.PRV}} ]; then
            echo "Version mismatch between main branch and pull request branch"
            exit 1
          fi
