name: Check Version Bump

on: [pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Get main version
        id: tm
        run: echo "MAINV=$(jq -r '.version' version.json)" >> $GITHUB_OUTPUT

      - name: Checkout PR
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Get PR version
        id: tpr
        run: echo "PRV=$(jq -r '.version' version.json)" >> $GITHUB_OUTPUT

      - name: Compare versions
        run: |
          status=$(bash semver.sh ${{steps.tpr.outputs.PRV}} ${{steps.tm.outputs.MAINV}})
          if ${status}; then
            echo "Version in PR should be greater than that declared in main's version.json"
            exit 1
          else
            echo "Version bump detected. Status Check passed"
          fi
