name: Check Version Bump

on: [push, pull_request]

env:
  BRANCH: ${{ github.head_ref || 'v1'}}

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Create directories
        run: |
          mkdir main
          mkdir ${BRANCH}
          ls

      - name: Checkout main
        uses: actions/checkout@v3
        with:
          ref: main
          path: main

      - name: Test main
        run: |
          ls
          jq -r '.version' main/version.json

      - name: Checkout PR
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          path: ${{ github.head_ref }}

      - name: Test PR
        run: |
          ls
          jq -r '.version' version.json

      - name: validate new version
        run: |
          ls
          bash semver.sh

      - name: Compare versions
        run: |
          main_version=$(jq -r '.version' main/version.json)
          pr_version=$(jq -r '.version' ${BRANCH}/version.json)
          if [ "$main_version" != "$pr_version" ]; then
            echo "Version mismatch between main branch and pull request branch"
            exit 1
          fi
